import React, { useState, useRef } from "react";
import { Link } from "react-router-dom";
import {
  ChevronLeft,
  Download,
  Loader2,
  ChevronDown,
  Globe,
  Users,
  Battery,
  BatteryWarning,
  Zap,
  Eye,
  CheckSquare,
  Square,
} from "lucide-react";
import { useDownloadReceipt } from "../hooks/useDownloadReceipt";

const TEXT = {
  zh: {
    title: "社交观察",
    subtitle: "// 社交日志小票",
    context: "交互情境",
    metrics: "状态诊断",
    analysis: "详细分析",

    labelSubject: "交互对象",
    labelType: "社交类型",
    labelLocation: "地点",
    labelDuration: "持续时间",

    labelBattery: "剩余电量 (Battery)",
    labelAwkward: "尴尬指数 (Cringe)",
    labelVibe: "氛围评分 (Vibe)",

    labelSummary: "总结摘要",
    labelVerdict: "结论 (Verdict)",

    // Preview Specific
    labelHeader: "社交观察",
    labelReportType: "诊断报告",
    labelConfidential: "绝密",
    labelLowBattery: "电量低",
    labelFooter: "由 Social_Lab v2.0 生成",

    download: "下载",
    downloading: "诊断中...",

    types: {
      DATE: "约会",
      PARTY: "聚会/派对",
      WORK: "工作/会议",
      FAMILY: "家庭聚餐",
      CASUAL: "闲聊",
      FORCED: "被迫营业",
    },
    verdicts: {
      RECHARGE: "急需充电",
      FUN: "意外有趣",
      BLOCK: "建议拉黑",
      AGAIN: "下次再约",
    },
  },
  en: {
    title: "SOCIAL_LAB",
    subtitle: "// SOCIAL LOG",
    context: "Interaction Context",
    metrics: "Diagnosis",
    analysis: "Detailed Analysis",

    labelSubject: "Subject(s)",
    labelType: "Interaction Type",
    labelLocation: "Location",
    labelDuration: "Duration",

    labelBattery: "Battery Lvl",
    labelAwkward: "Cringe Lvl",
    labelVibe: "Vibe Check",

    labelSummary: "Summary",
    labelVerdict: "Verdict",

    // Preview Specific
    labelHeader: "SOCIAL_LAB",
    labelReportType: "Diagnosis Report",
    labelConfidential: "CONFIDENTIAL",
    labelLowBattery: "LOW",
    labelFooter: "Generated by Social_Lab v2.0",

    download: "PRINT REPORT",
    downloading: "ANALYZING...",

    types: {
      DATE: "Date",
      PARTY: "Party",
      WORK: "Work/Meeting",
      FAMILY: "Family Dinner",
      CASUAL: "Hangout",
      FORCED: "Forced Social",
    },
    verdicts: {
      RECHARGE: "Need Recharge",
      FUN: "Surprisingly Fun",
      BLOCK: "Block Them",
      AGAIN: "Let's Meet Again",
    },
  },
};

const InputSection = ({ title, children, isOpen, onToggle }) => (
  <div
    className={`border border-gray-200 rounded-lg bg-white overflow-hidden transition-all duration-300 mb-3 ${
      isOpen ? "shadow-md ring-1 ring-black/5" : "hover:border-gray-300"
    }`}
  >
    <button
      onClick={onToggle}
      className="flex items-center justify-between w-full p-4 text-left transition-colors bg-white hover:bg-gray-50"
    >
      <h3
        className={`text-sm font-bold uppercase tracking-wider ${
          isOpen ? "text-black" : "text-gray-600"
        }`}
      >
        {title}
      </h3>
      <div
        className={`text-gray-400 transition-transform duration-300 ${
          isOpen ? "rotate-180 text-black" : ""
        }`}
      >
        <ChevronDown size={18} />
      </div>
    </button>
    <div
      className={`transition-all duration-300 ease-in-out ${
        isOpen ? "max-h-[600px] opacity-100" : "max-h-0 opacity-0"
      }`}
    >
      <div className="p-4 pt-0 border-t border-gray-50">
        <div className="pt-4 space-y-4">{children}</div>
      </div>
    </div>
  </div>
);

const InputGroup = ({
  label,
  value,
  onChange,
  placeholder,
  isTextArea = false,
}) => {
  const handleTextareaChange = (e) => {
    // Update the value
    onChange(e.target.value);

    // Automatically adjust the textarea height
    const textarea = e.target;
    textarea.style.height = "auto"; // Reset height to calculate the new one
    textarea.style.height = `${Math.min(textarea.scrollHeight, 300)}px`; // Set height to scroll height, max 300px
  };

  return (
    <div>
      <label className="block text-[10px] font-bold text-gray-400 mb-1.5 uppercase tracking-wide">
        {label}
      </label>
      {isTextArea ? (
        <textarea
          value={value}
          onChange={handleTextareaChange}
          onInput={handleTextareaChange} // Also handle paste and other input events
          placeholder={placeholder}
          className="w-full bg-gray-50 border border-gray-200 p-2.5 text-sm focus:border-black focus:ring-1 focus:ring-black outline-none rounded-sm resize-none h-auto min-h-[6rem] block transition-all"
          style={{ overflow: "hidden" }} // Hide scrollbar while auto-resizing
        />
      ) : (
        <input
          type="text"
          value={value}
          onChange={(e) => onChange(e.target.value)}
          placeholder={placeholder}
          className="w-full bg-gray-50 border border-gray-200 p-2.5 text-sm focus:border-black focus:ring-1 focus:ring-black outline-none rounded-sm block transition-all"
        />
      )}
    </div>
  );
};

const SliderItem = ({ label, value, onChange, icon: Icon }) => (
  <div className="flex items-center gap-3">
    <div className="flex items-center w-24 gap-2 text-gray-500">
      {Icon && <Icon size={14} />}
      <span className="text-[10px] font-bold uppercase truncate">{label}</span>
    </div>
    <input
      type="range"
      min="0"
      max="100"
      value={value}
      onChange={(e) => onChange(parseInt(e.target.value))}
      className="flex-1 h-1 bg-gray-200 rounded-lg appearance-none cursor-pointer accent-black"
    />
    <span className="w-8 font-mono text-xs font-bold text-right text-gray-900">
      {value}%
    </span>
  </div>
);

export default function SocialReceiptPage() {
  const [lang, setLang] = useState("zh");
  const [mobileTab, setMobileTab] = useState("edit");
  const [data, setData] = useState({
    subject: "相亲对象 A",
    type: "DATE",
    location: "某网红咖啡馆",
    duration: "2h",
    battery: 15,
    awkward: 85,
    vibe: 30,
    summary:
      "全程都在聊他的加密货币投资，完全没有问过我的情况。咖啡很难喝，气氛很尴尬。我想回家打游戏。",
    verdict: "RECHARGE",
  });

  const [expandedSection, setExpandedSection] = useState("context");
  const receiptRef = useRef(null);
  const { isDownloading, handleDownload, error } = useDownloadReceipt('SOCIAL_LOG');
  const t = TEXT[lang];
  const toggleLang = () => setLang((l) => (l === "zh" ? "en" : "zh"));
  const toggleSection = (s) =>
    setExpandedSection(expandedSection === s ? null : s);

  return (
    <div className="fixed inset-0 flex flex-col overflow-hidden font-mono text-gray-900 bg-gray-100 md:flex-row md:justify-center">
      {/* Editor */}
      <div
        className={`w-full md:w-[450px] flex flex-col h-full bg-white  z-10 transition-transform duration-300 ${
          mobileTab === "edit"
            ? "translate-x-0"
            : "-translate-x-full md:translate-x-0"
        } absolute md:relative`}
      >
        <header className="flex items-center justify-between p-4 bg-white border-b border-gray-100 shrink-0">
          <div className="flex items-center gap-3">
            <Link
              to="/"
              className="p-2 transition-colors rounded-full hover:bg-gray-100"
            >
              <ChevronLeft size={18} />
            </Link>
            <div className="flex-1 min-w-0">
              <h1 className="text-lg font-black tracking-wider text-gray-900 truncate">
                {t.title}
              </h1>
              <p className="overflow-hidden text-xs font-bold text-gray-400 whitespace-nowrap text-ellipsis">
                {t.subtitle}
              </p>
            </div>
          </div>
          <button
            onClick={toggleLang}
            className="flex items-center gap-1 px-2 py-1 text-xs font-bold bg-gray-100 rounded hover:bg-gray-200 shrink-0"
          >
            <Globe size={12} /> {lang === "zh" ? "EN" : "中文"}
          </button>
        </header>

        <div className="flex-1 p-4 pb-24 space-y-3 overflow-y-auto md:pb-10 no-scrollbar">
          <style>{`.no-scrollbar::-webkit-scrollbar { display: none; } .no-scrollbar { -ms-overflow-style: none; scrollbar-width: none; }`}</style>
          <InputSection
            title={t.context}
            isOpen={expandedSection === "context"}
            onToggle={() => toggleSection("context")}
          >
            <InputGroup
              label={t.labelSubject}
              value={data.subject}
              onChange={(v) => setData({ ...data, subject: v })}
            />
            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="block text-[10px] font-bold text-gray-400 mb-1.5 uppercase">
                  {t.labelType}
                </label>
                <select
                  value={data.type}
                  onChange={(e) => setData({ ...data, type: e.target.value })}
                  className="w-full bg-gray-50 border border-gray-200 p-2.5 text-sm focus:border-black outline-none rounded-sm"
                >
                  {Object.entries(t.types).map(([key, label]) => (
                    <option key={key} value={key}>
                      {label}
                    </option>
                  ))}
                </select>
              </div>
              <InputGroup
                label={t.labelDuration}
                value={data.duration}
                onChange={(v) => setData({ ...data, duration: v })}
              />
            </div>
            <InputGroup
              label={t.labelLocation}
              value={data.location}
              onChange={(v) => setData({ ...data, location: v })}
            />
          </InputSection>

          <InputSection
            title={t.metrics}
            isOpen={expandedSection === "metrics"}
            onToggle={() => toggleSection("metrics")}
          >
            <div className="p-4 space-y-4 border border-gray-100 rounded-sm bg-gray-50">
              <SliderItem
                label={t.labelBattery}
                value={data.battery}
                onChange={(v) => setData({ ...data, battery: v })}
                icon={Battery}
              />
              <SliderItem
                label={t.labelAwkward}
                value={data.awkward}
                onChange={(v) => setData({ ...data, awkward: v })}
                icon={BatteryWarning}
              />
              <SliderItem
                label={t.labelVibe}
                value={data.vibe}
                onChange={(v) => setData({ ...data, vibe: v })}
                icon={Zap}
              />
            </div>
          </InputSection>

          <InputSection
            title={t.analysis}
            isOpen={expandedSection === "analysis"}
            onToggle={() => toggleSection("analysis")}
          >
            <InputGroup
              label={t.labelSummary}
              value={data.summary}
              onChange={(v) => setData({ ...data, summary: v })}
              isTextArea
            />
            <div>
              <label className="block text-[10px] font-bold text-gray-400 mb-1.5 uppercase">
                {t.labelVerdict}
              </label>
              <div className="grid grid-cols-2 gap-2">
                {Object.entries(t.verdicts).map(([key, label]) => (
                  <button
                    key={key}
                    onClick={() => setData({ ...data, verdict: key })}
                    className={`p-2 text-xs border rounded-sm text-left flex items-center gap-2 transition-all ${
                      data.verdict === key
                        ? "bg-black text-white border-black"
                        : "bg-white border-gray-200 text-gray-600 hover:border-gray-300"
                    }`}
                  >
                    {data.verdict === key ? (
                      <CheckSquare size={14} />
                    ) : (
                      <Square size={14} />
                    )}
                    {label}
                  </button>
                ))}
              </div>
            </div>
          </InputSection>
          <div className="h-10 md:hidden"></div>
        </div>
      </div>

      {/* Preview */}
      <div
        className={`w-full md:w-[450px] bg-gray-200 relative z-0 transition-transform duration-300 ${
          mobileTab === "preview"
            ? "translate-x-0"
            : "translate-x-full md:translate-x-0"
        } absolute md:relative h-full`}
      >
        <div className="absolute inset-0 pointer-events-none opacity-5 bg-[radial-gradient(#000_1px,transparent_1px)] [background-size:16px_16px]"></div>
        <div className="absolute z-20 top-4 right-4">
          <button
            onClick={() => handleDownload(receiptRef)}
            disabled={isDownloading}
            className="bg-black text-white px-5 py-2.5 rounded-full shadow-xl hover:bg-gray-800 transition-all flex items-center gap-2 text-xs font-bold tracking-widest"
          >
            {isDownloading ? (
              <Loader2 size={14} className="animate-spin" />
            ) : (
              <Download size={14} />
            )}
            {isDownloading ? t.downloading : t.download}
          </button>
        </div>

        <div className="w-full h-full overflow-y-auto no-scrollbar">
          <div className="flex items-center justify-center min-h-full py-20 md:py-10">
            <div className="transition-transform duration-500 origin-top scale-90 receipt-wrapper sm:scale-100">
              <SocialPreview data={data} text={t} ref={receiptRef} />
            </div>
          </div>
        </div>
      </div>

      {/* Mobile Tab Bar */}
      <div className="md:hidden fixed bottom-6 left-1/2 -translate-x-1/2 z-50 bg-black text-white rounded-full px-1.5 py-1.5 shadow-2xl flex gap-1">
        <button
          onClick={() => setMobileTab("edit")}
          className={`flex items-center gap-2 px-4 py-2 rounded-full text-xs font-bold transition-all ${
            mobileTab === "edit"
              ? "bg-white text-black"
              : "text-gray-400 hover:text-white"
          }`}
        >
          <Users size={14} /> 编辑
        </button>
        <button
          onClick={() => setMobileTab("preview")}
          className={`flex items-center gap-2 px-4 py-2 rounded-full text-xs font-bold transition-all ${
            mobileTab === "preview"
              ? "bg-white text-black"
              : "text-gray-400 hover:text-white"
          }`}
        >
          <Eye size={14} /> 预览
        </button>
      </div>
    </div>
  );
}

const SocialPreview = React.forwardRef(({ data, text }, ref) => {
  return (
    <div ref={ref} className="w-[380px] relative">
      <div className="min-h-[600px] bg-white p-6 pb-8 font-mono flex flex-col">
        {/* Header */}
        <div className="mb-4 text-center">
          <h1 className="mb-1 text-3xl font-bold tracking-wider text-black">
            {text.labelHeader}
          </h1>
          <div className="text-[10px] font-bold text-gray-500 tracking-widest">
            {text.subtitle}
          </div>
        </div>
        <div className="my-2 border-t-2 border-black border-dashed"></div>

        {/* Subject Info */}
        {data.subject && data.subject.trim() && (
          <div className="mb-6">
            <div className="grid grid-cols-2 mb-4 text-sm gap-y-1">
              <div className="font-bold text-gray-500">
                {text.labelSubject}:
              </div>
              <div className="text-right truncate">{data.subject}</div>
              <div className="font-bold text-gray-500">{text.labelType}:</div>
              <div className="text-right truncate">{text.types[data.type]}</div>
              <div className="font-bold text-gray-500">
                {text.labelLocation}:
              </div>
              <div className="text-right truncate">{data.location}</div>
              <div className="font-bold text-gray-500">
                {text.labelDuration}:
              </div>
              <div className="text-right truncate">{data.duration}</div>
            </div>
          </div>
        )}

        <div className="my-2 border-t-2 border-black border-dashed"></div>

        {/* Battery Status */}
        <div className="mb-4">
          <div className="flex justify-between mb-1 text-xs font-bold uppercase">
            <span>{text.labelBattery}</span>
            <span>{data.battery}%</span>
          </div>
          <div className="relative h-2 bg-gray-200 border border-black">
            <div
              className="h-full transition-all bg-black"
              style={{ width: `${data.battery}%` }}
            ></div>
          </div>
        </div>

        {/* Other Metrics */}
        <div className="mb-6 space-y-4">
          <div>
            <div className="flex justify-between mb-1 text-xs font-bold uppercase">
              <span>{text.labelAwkward}</span>
              <span>{data.awkward}%</span>
            </div>
            <div className="relative h-2 bg-gray-200 border border-black">
              <div
                className="h-full transition-all bg-black"
                style={{ width: `${data.awkward}%` }}
              ></div>
            </div>
          </div>
          <div>
            <div className="flex justify-between mb-1 text-xs font-bold uppercase">
              <span>{text.labelVibe}</span>
              <span>{data.vibe}%</span>
            </div>
            <div className="relative h-2 bg-gray-200 border border-black">
              <div
                className="h-full transition-all bg-black"
                style={{ width: `${data.vibe}%` }}
              ></div>
            </div>
          </div>
        </div>

        {/* Summary */}
        {data.summary && data.summary.trim() && (
          <div className="mb-6">
            <div className="text-[10px] font-bold uppercase text-gray-500 border-b border-black pb-1 mb-2">
              {text.labelSummary}
            </div>
            <p className="text-sm leading-relaxed whitespace-pre-wrap">
              {data.summary}
            </p>
          </div>
        )}

        {/* Verdict - 2x2 Grid */}
        <div className="mb-6">
          <div className="text-[10px] font-bold uppercase text-gray-500 border-b border-black pb-1 mb-2">
            {text.labelVerdict}
          </div>
          <div className="grid grid-cols-2 gap-4 text-sm">
            {Object.entries(text.verdicts).map(([k, v]) => (
              <div key={k} className="flex items-center gap-2">
                <span>{data.verdict === k ? "☑" : "□"}</span>
                <span>{v}</span>
              </div>
            ))}
          </div>
        </div>

        <div className="my-2 border-t-2 border-black border-dashed"></div>

        {/* Footer */}
        <div className="flex flex-col items-center pt-6 mt-auto">
          <div className="text-[10px] font-bold uppercase tracking-widest mb-2 text-center">
            End of Social Analysis Report
          </div>
          <div className="flex items-center justify-between w-full h-12 overflow-hidden">
            {/* Barcode pattern */}
            {[...Array(32)].map((_, i) => (
              <div
                key={i}
                className="h-full bg-black"
                style={{
                  width: Math.random() > 0.5 ? "2px" : "4px",
                  marginLeft: "1px",
                }}
              ></div>
            ))}
          </div>
          <div className="text-[10px] mt-1 font-mono">
            {Date.now().toString().slice(-8)}
          </div>
        </div>
      </div>

      {/* Zigzag */}
      <div className="w-full h-3 overflow-hidden">
        <svg
          width="100%"
          height="100%"
          preserveAspectRatio="none"
          className="block"
        >
          <defs>
            <pattern
              id="zag"
              x="0"
              y="0"
              width="20"
              height="100%"
              patternUnits="userSpaceOnUse"
            >
              <path d="M0 0 L10 12 L20 0 Z" fill="white" />
            </pattern>
          </defs>
          <rect width="100%" height="100%" fill="url(#zag)" />
        </svg>
      </div>
    </div>
  );
});
